[build-system]
requires = [
    "setuptools==80.9.0",
]
build-backend = "setuptools.build_meta"

[project]
name = "beeware-docs-tools"
version = "2025.08.15.0"
description = "Tools for building BeeWare's documentation with a common theme and translations."
readme = "README.md"
requires-python = ">= 3.12"
license = "BSD-3-Clause"
license-files = [
    "LICENSE",
]
authors = [
    {name="Kattni", email="kattni@kattni.com"},
]
maintainers = [
    {name="BeeWare Team", email="team@beeware.org"},
]

dependencies = [
    "markdown-checker==0.2.5",
    "mistletoe==1.4.0",
    "mkdocs-autorefs==1.4.2",
    "mkdocs-include-markdown-plugin==7.1.6",
    "mkdocs-literate-nav==0.6.2",
    "mkdocs-macros-plugin==1.3.7",
    "mkdocs-material==9.6.17",
    "mkdocs==1.6.1",
    "pymdown-extensions==10.16",
    "pyspelling==2.10",
    "python-Levenshtein==0.27.1",
    "PyYAML==6.0.2",
    "setuptools-scm==9.2.0",
    "translate-toolkit @ git+https://github.com/translate/translate@aa35159f03f53aa536381643dfafbc2a19a24784",
]

[project.optional-dependencies]
# Extras used by developers *of* beeware-docs-tools are pinned to specific versions to
# ensure environment consistency.
dev = [
    "pre-commit == 4.2.0",
    "tox-uv == 1.28.0",
]

[project.urls]
Homepage = "https://beeware.org/"
Funding = "https://beeware.org/contributing/membership/"
Tracker = "https://github.com/beeware/beeware-docs-tools/issues/"
Source = "https://github.com/beeware/beeware-docs-tools/"

[project.scripts]
build_md_translations = "beeware_docs_tools.build_md_translations:main"
build_po_translations = "beeware_docs_tools.build_po_translations:main"
live_serve_en = "beeware_docs_tools.live_serve_en:main"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
beeware_docs_tools = [
    "**/*.html",
    "**/*.css",
    "**/*.js",
    "**/*.png",
    "**/*.woff2",
]
